builds:
  - binary: goimportssort
    goos:
      - linux
      - freebsd
      - darwin
    goarch:
      - amd64
      - arm64
    dir: .
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    flags:
      - -trimpath