//go:build ignore

// Command gen_stdpackages regenerates standardpackages_generated.go, the set of
// public standard library import paths embedded at build time. isStandardPackage
// uses it as a fallback when GOROOT/src is not available for a filesystem lookup.
//
// Run via: go generate ./...
package main

import (
	"bytes"
	"go/format"
	"log"
	"os"
	"os/exec"
	"runtime"
	"sort"
	"strings"
	"text/template"
)

// isPublic reports whether an import path is importable from outside the
// standard library, i.e. it contains neither an internal nor a vendor element.
func isPublic(pkg string) bool {
	for _, element := range strings.Split(pkg, "/") {
		if element == "internal" || element == "vendor" {
			return false
		}
	}
	return true
}

func main() {
	out, err := exec.Command("go", "list", "std").Output()
	if err != nil {
		log.Fatalf("go list std: %v", err)
	}

	var packages []string
	for _, line := range strings.Split(strings.TrimSpace(string(out)), "\n") {
		if line != "" && isPublic(line) {
			packages = append(packages, line)
		}
	}
	sort.Strings(packages)

	data := struct {
		GoVersion string
		Packages  []string
	}{
		GoVersion: runtime.Version(),
		Packages:  packages,
	}

	var buf bytes.Buffer
	if err := fileTemplate.Execute(&buf, data); err != nil {
		log.Fatalf("execute template: %v", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatalf("format source: %v", err)
	}

	if err := os.WriteFile("standardpackages_generated.go", formatted, 0o644); err != nil {
		log.Fatalf("write file: %v", err)
	}
}

var fileTemplate = template.Must(template.New("").Parse(`// Code generated by gen_stdpackages.go from {{.GoVersion}}; DO NOT EDIT.

package main

// standardPackagesGoVersion is the Go toolchain version whose standard library
// the embedded set below was generated from.
const standardPackagesGoVersion = "{{.GoVersion}}"

// standardPackages is the set of public standard library import paths, embedded
// at build time. isStandardPackage consults it as a fallback when GOROOT/src is
// unavailable for a filesystem lookup.
var standardPackages = map[string]struct{}{
{{- range .Packages}}
	"{{.}}": {},
{{- end}}
}
`))
