---
name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7

      - name: Verify generated files are up to date
        run: |
          go generate ./...
          git diff --exit-code

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...